#!/bin/bash
# EC2 user-data bootstrap script (Amazon Linux 2023)
# Generated by Terraform templatefile — do not edit directly.
# Source: infra/terraform/ec2/userdata.sh.tpl
#
# What it does:
#   1. Installs Docker + Docker Compose plugin
#   2. Clones the repo
#   3. Writes a .env file with JWT_SECRET
#   4. Runs docker compose -f docker-compose.ec2.yml up --build
#
# Monitor progress: tail -f /var/log/ec2-userdata.log

set -euo pipefail
exec > >(tee -a /var/log/ec2-userdata.log) 2>&1

echo "=== EC2 bootstrap started: $(date) ==="

# ── 1. System packages ────────────────────────────────────────────────────────
dnf update -y
dnf install -y docker git

# ── 2. Docker daemon ──────────────────────────────────────────────────────────
systemctl enable --now docker
usermod -aG docker ec2-user

# ── 3. Docker Compose plugin ──────────────────────────────────────────────────
COMPOSE_DIR=/usr/local/lib/docker/cli-plugins
mkdir -p "$COMPOSE_DIR"
curl -fsSL \
  "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64" \
  -o "$COMPOSE_DIR/docker-compose"
chmod +x "$COMPOSE_DIR/docker-compose"
docker compose version

# ── 4. Clone repository ───────────────────────────────────────────────────────
APP_DIR=/home/ec2-user/app
git clone --branch "${github_branch}" --depth 1 \
  "${github_repo_url}" "$APP_DIR"
chown -R ec2-user:ec2-user "$APP_DIR"

# ── 5. Environment file ───────────────────────────────────────────────────────
cat > "$APP_DIR/Chapter04/.env" << ENVEOF
JWT_SECRET=${jwt_secret}
AWS_REGION=${aws_region}
ENVEOF
chown ec2-user:ec2-user "$APP_DIR/Chapter04/.env"

# ── 6. Build & start the full stack ──────────────────────────────────────────
# Runs as ec2-user so docker socket permissions are correct.
# Build takes ~5 minutes on first boot (compiling 6 images).
cd "$APP_DIR/Chapter04"
docker compose -f docker-compose.ec2.yml up -d --build

echo "=== EC2 bootstrap complete: $(date) ==="
echo "Landing page: http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)"
