#!/bin/bash
# EC2 user-data bootstrap script (Amazon Linux 2023)
# Generated by Terraform templatefile — do not edit directly.
# Source: infra/terraform/ec2/userdata.sh.tpl
#
# What it does:
#   1. Installs Docker + Docker Compose plugin
#   2. Clones the repo
#   3. Writes a .env file with JWT_SECRET
#   4. Runs docker compose -f docker-compose.ec2.yml up --build
#
# Monitor progress: tail -f /var/log/ec2-userdata.log

set -euo pipefail
exec > >(tee -a /var/log/ec2-userdata.log) 2>&1

echo "=== EC2 bootstrap started: $(date) ==="

# ── 1. System packages ────────────────────────────────────────────────────────
dnf update -y
dnf install -y docker git

# ── 2. Docker daemon ──────────────────────────────────────────────────────────
systemctl enable --now docker
usermod -aG docker ec2-user

# ── 3. Docker Compose plugin ──────────────────────────────────────────────────
COMPOSE_DIR=/usr/local/lib/docker/cli-plugins
mkdir -p "$COMPOSE_DIR"
curl -fsSL \
  "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64" \
  -o "$COMPOSE_DIR/docker-compose"
chmod +x "$COMPOSE_DIR/docker-compose"
docker compose version

# ── 3b. Docker Buildx plugin (Compose v5 requires 0.17+) ─────────────────────
BUILDX_DIR=/root/.docker/cli-plugins
mkdir -p "$BUILDX_DIR"
curl -fsSL \
  "https://github.com/docker/buildx/releases/download/v0.23.0/buildx-v0.23.0.linux-amd64" \
  -o "$BUILDX_DIR/docker-buildx"
chmod +x "$BUILDX_DIR/docker-buildx"
# Also install for ec2-user
mkdir -p /home/ec2-user/.docker/cli-plugins
cp "$BUILDX_DIR/docker-buildx" /home/ec2-user/.docker/cli-plugins/docker-buildx
chown ec2-user:ec2-user /home/ec2-user/.docker/cli-plugins/docker-buildx
docker buildx version

# ── 4. Clone repository ───────────────────────────────────────────────────────
APP_DIR=/home/ec2-user/app
git clone --branch "${github_branch}" --depth 1 \
  "${github_repo_url}" "$APP_DIR"
chown -R ec2-user:ec2-user "$APP_DIR"

# ── 5. Environment file ───────────────────────────────────────────────────────
cat > "$APP_DIR/Chapter04/.env" << ENVEOF
JWT_SECRET=${jwt_secret}
AWS_REGION=${aws_region}
ENVEOF
chown ec2-user:ec2-user "$APP_DIR/Chapter04/.env"

# ── 6. Build & start the full stack ──────────────────────────────────────────
# Runs as ec2-user so docker socket permissions are correct.
# Build takes ~5 minutes on first boot (compiling 6 images).
cd "$APP_DIR/Chapter04"
docker compose -f docker-compose.ec2.yml up -d --build

# ── 7. Systemd service — auto-start containers on every boot ─────────────────
cat > /etc/systemd/system/healthcare-stack.service << 'SVCEOF'
[Unit]
Description=Healthcare Docker Compose Stack
Requires=docker.service
After=docker.service network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=/home/ec2-user/app/Chapter04
ExecStart=/usr/local/lib/docker/cli-plugins/docker-compose -f docker-compose.ec2.yml up -d
ExecStop=/usr/local/lib/docker/cli-plugins/docker-compose -f docker-compose.ec2.yml down
User=ec2-user
Group=ec2-user

[Install]
WantedBy=multi-user.target
SVCEOF

systemctl daemon-reload
systemctl enable healthcare-stack.service
echo "Auto-start service enabled"

echo "=== EC2 bootstrap complete: $(date) ==="
echo "Landing page: http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)"
