apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
  namespace: healthcare
  labels:
    app: flask-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
        - name: flask-backend
          image: localhost:5000/flask-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4001
          envFrom:
            - configMapRef:
                name: microservices-config
            - secretRef:
                name: microservices-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: flask-backend
  namespace: healthcare
spec:
  selector:
    app: flask-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
      nodePort: 30006
