apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - glue-catalog.yaml
  - claims-generator.yaml
  - claims-cleaner.yaml
  - sqs-monitor.yaml
  - athena-client.yaml
  - patients-encounters.yaml
  - flask-backend.yaml
  - spring-boot-backend.yaml
