apiVersion: v1
kind: Secret
metadata:
  name: microservices-secret
  namespace: healthcare
type: Opaque
stringData:
  JWT_SECRET: "health-care-dev-secret"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
